server:
  port: 8080

swagger:
  enabled: true


spring:
  datasource:
    username: uporabnik
    password: geslo
    url: jdbc:postgresql://localhost:5432/avtoIskalnik
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
  session:
    store-type: none
  main:
    allow-bean-definition-overriding: true


management:
  endpoints:
    web:
      exposure:
        include=*: